apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: vpa
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    admissionController:
      enabled: true
      generateCertificate: true
      secretName: vpa-webhook-certs
      cleanupOnDelete: true
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 500Mi
      pdb:
        minAvailable: 1
    recommender:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 1Gi
      extraArgs:
        storage: prometheus
        prometheus-address: 'http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090'
        prometheus-cadvisor-job-name: kubelet
        memory-saver: true
      pdb:
        minAvailable: 1
    updater:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 500Mi
      extraArgs:
        min-replicas: 2
        eviction-tolerance: 0.5
      pdb:
        minAvailable: 1
    mutatingWebhookConfiguration:
      failurePolicy: Ignore
    rbac:
      create: true
    serviceAccount:
      create: true
    priorityClassName: system-cluster-critical
    nodeSelector: {}
    tolerations: []
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - vpa
              topologyKey: kubernetes.io/hostname
    metrics:
      serviceMonitor:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
