---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: goldilocks
      version: 8.0.3
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    # Image configuration
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v8.0.2
      pullPolicy: IfNotPresent
    
    # Controller configuration
    controller:
      enabled: true
      
      rbac:
        create: true
        
      serviceAccount:
        create: true
        name: goldilocks-controller
        
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
          
      # Flags for controller
      flags:
        on-by-default: false  # Don't enable VPA for all namespaces by default
        exclude-containers: "linkerd-proxy,istio-proxy"  # Exclude service mesh sidecars
        
      deployment:
        replicas: 1
        
        # Anti-affinity for HA
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - goldilocks-controller
                  topologyKey: kubernetes.io/hostname
    
    # Dashboard configuration
    dashboard:
      enabled: true
      
      replicaCount: 1
      
      service:
        type: ClusterIP
        port: 80
        targetPort: 8080
        
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
          
      deployment:
        annotations:
          reloader.stakater.com/auto: "true"
          
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
        
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
        capabilities:
          drop:
            - ALL
            
      # Dashboard flags
      flags:
        exclude-containers: "linkerd-proxy,istio-proxy"
    
    # Enable VPA for specific namespaces only
    # Use namespace labels: goldilocks.fairwinds.com/enabled=true
    installVPA: false  # We've already installed VPA separately
    
    # Uninstall VPA objects when Goldilocks is removed
    uninstallVPA: false