apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-secret
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: test-secret
  interval: 30m
  timeout: 10m
  prune: true
  wait: true
  path: ./kubernetes/apps/default/test-secret/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
